repos:
-   repo: https://github.com/PyCQA/pylint
    rev: 'v2.16.2' #Use the latest version
    hooks:
    -   id: pylint
-   repo: https://github.com/psf/black
    rev: '23.7.0' #Use the latest version
    hooks:
    -   id: black
